import logo from '../public/assets/logo.png'
import profile from '../public/assets/profile.png'
import circle from '../public/assets/circle.svg'
import about01 from '../public/assets/about01.png'
import about02 from '../public/assets/about02.png'
import about03 from '../public/assets/about03.png'
import about04 from '../public/assets/about04.png'
import html from '../public/assets/html.png'
import css from '../public/assets/css.png'
import react from '../public/assets/react.png'
import javascript from '../public/assets/javascript.png'
import git from '../public/assets/git.png'
import email from '../public/assets/email.png'
import mobile from '../public/assets/mobile.png'
export default {logo,profile,circle,about01,about02,about03,about04,html,css,react,javascript,git,email,mobile};